### PR TITLE
Add StaticTrace function for tracing a specific TTL node in a specific timeout

### PR DESCRIPTION
**Pull request by SgtDaJim**
Like I said in the former issue, I am making a MTR in golang. Sometimes, a few nodes in the route aren't unreachable. It might be the timeout is too short. So in my program, I will try to ping the specific TTL nodes in different increasing timeout if they seem to be unreachable in the first trace. So I add this StaticTrace function.

### CODE REVIEW

**Comment by pixelbender** [comment]
Wait, definitely there is a more optimal way to do MTR-like probes reusing channels, listeners etc...

**Comment by SgtDaJim** [comment]
So do you have any suggestions? This is my program [op-mtr](https://github.com/SgtDaJim/op-mtr/blob/master/mtr/mtr.go). You can have a look.

**Comment by SgtDaJim** [comment]
And could you tell me your contact information? We can talk about this more conveniently

**Comment by pixelbender** [comment]
@SgtDaJim Just added custom tracing session support, so you can send probes and receive responses. See https://godoc.org/github.com/pixelbender/go-traceroute/traceroute#Session
You can reach me at https://telegram.me/pixelbender

**Comment by SgtDaJim** [comment]
I am using a Chinese phone number..so I can not reach you by tg in private contact..
Anyway, thanks for your work, I will test the code tomorrow

**Pull request closed without merging**
